name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: 
  - bug
  - triage
body:
- type: checkboxes
  attributes:
    label: Bug Report Checklist
    description: Please ensure that you have completed the following steps before submitting your bug report.
    options:
      - label: I have searched the issue tracker for similar reports
        required: true
      - label: I have included steps to reproduce the bug
        required: true
      - label: I have attached relevant error logs (if applicable)
        required: true
      - label: I have provided my environment details
        required: true
      - label: I agree to the contributor guidelines and code of conduct as outlined in the project's documentation
        required: true
- type: input
  attributes:
    label: Title
    description: A short, descriptive title for the bug.
    placeholder: "Example: Crash on startup"
  validations:
    required: true
- type: textarea
  attributes:
    label: Summary
    description: A short summary of the bug.
    placeholder: "Example: Crash on startup"
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to Reproduce
    description: A list of steps to reproduce the bug.
    placeholder: |-
      1. Open the application
      2. Click on the 'Submit' button
      3. See the error message
    render: markdown
  validations:
    required: true
- type: input
  attributes:
    label: Expected Behavior
    description: A description of what you expected to happen.
    placeholder: "Example: The application should submit the form without errors."
  validations:
    required: true
- type: textarea
  attributes:
    label: Error Logs
    description: Any error messages or logs that were generated during the bug occurrence.
    placeholder: "Example: Error logs from the console"
    render: markdown
- type: textarea
  attributes:
    label: Additional Context
    description: Any other context or information that might be relevant to the bug report.
    placeholder: "Example: This bug occurs only on mobile devices or console outputs"
    render: markdown
- type: dropdown
  attributes:
    label: Operating System
    description: What operating system are you using?
    options:
      - OSX (MacOS)
      - Windows
      - Ubuntu
      - Debian
      - Fedora
      - Arch Linux
      - BSD-based System
      - Other
  validations:
    required: true
- type: input
  attributes:
    label: Version
    description: What version of our software are you running?
    placeholder: "Example: 1.0.2"
  validations:
    required: true
- type: markdown
  attributes:
    value: "Thanks for completing our form!"
