name: Feature Request
description: File a feature request.
title: "[Feature]: "
labels: 
  - feature
  - triage
body:
- type: checkboxes
  attributes:
    label: Feature Request Checklist
    description: Please ensure that you have completed the following steps before submitting your feature request.
    options:
      - label: I have searched the issue tracker for similar requests
        required: true
      - label: I agree to the contributor guidelines and code of conduct as outlined in the project's documentation
        required: true
- type: input
  attributes:
    label: Feature Title
    description: A short, descriptive title for the feature request.
    placeholder: "Example: User Authentication"
  validations:
    required: true
- type: textarea
  attributes:
    label: Feature Description
    description: A detailed description of the feature.
    placeholder: "Example: This feature allows users to authenticate using OAuth."
  validations:
    required: true
- type: markdown
  attributes:
    value: "Thanks for completing our form!"
